services:
  mongo:
    image: mongo:8.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: EasyGenTaskDB
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
  # backend:
  #   build:
  #     context: ./apps/backend
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   env_file:
  #     - ./apps/backend/.env
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mongo

volumes:
  mongo-data:
